# Generated by Django 3.1.7 on 2021-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210306_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=15, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=638, max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
