# Generated by Django 3.1.7 on 2021-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210306_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='faxno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobileno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell Phone Number'),
        ),
    ]
