# Generated by Django 3.1.7 on 2021-03-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210306_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='annualrev',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Annual Revenue'),
        ),
        migrations.AddField(
            model_name='customer',
            name='noemployee',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Number of Employees'),
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadowner', models.CharField(max_length=20, verbose_name='Lead Owner')),
                ('title', models.CharField(max_length=100, verbose_name='Lead Title')),
                ('source', models.CharField(choices=[('Web', 'Web'), ('Campain', 'marketing'), ('Customer', 'custreq')], default='Web', max_length=100, verbose_name='Lead Source')),
                ('status', models.CharField(choices=[('Open', 'open'), ('Contacted', 'contacted'), ('Dropped', 'dropped'), ('Qutation submitted', 'qutation submitted'), ('Pending', 'pending'), ('Win', 'win'), ('Lost', 'lost')], default='Open', max_length=100, verbose_name='Status')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
    ]
