# Generated by Django 3.1.7 on 2021-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210306_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='annualrev',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Annual Revenue'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=15, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Industry Sector'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='noemployee',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=15, verbose_name='State/Proviance'),
        ),
    ]
