# Generated by Django 3.1.7 on 2021-03-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210306_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='createdby',
            field=models.CharField(default='Marketing', max_length=25, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='lead',
            name='modby',
            field=models.CharField(default='Sales', max_length=15, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], default='Cold', max_length=20, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='salesdesc',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Drop', 'Drop')], default='Qualified', max_length=15, verbose_name='Sales Opinion'),
        ),
        migrations.AddField(
            model_name='lead',
            name='value',
            field=models.CharField(default='0', max_length=15, verbose_name='Value $'),
        ),
    ]
