# Generated by Django 3.1.7 on 2021-04-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20210307_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=10, null=True, verbose_name='Job Title')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], default='Mr', max_length=10, null=True, verbose_name='Title')),
                ('fname', models.CharField(blank=True, max_length=10, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=10, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('faxno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax Number')),
                ('mobileno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell Phone Number')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
    ]
