# Generated by Django 3.1.7 on 2021-04-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fname',
            field=models.CharField(max_length=10, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='jobtitle',
            field=models.CharField(max_length=10, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='lname',
            field=models.CharField(max_length=10, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], default='Mr', max_length=10, verbose_name='Title'),
        ),
    ]
