# Generated by Django 3.1.7 on 2021-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20210410_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campainname', models.CharField(max_length=30, verbose_name='Campain Name')),
                ('budget', models.CharField(max_length=15, verbose_name='Budget ($)')),
                ('about', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=30, verbose_name='Campain About')),
                ('createdby', models.CharField(max_length=15, verbose_name='Created By')),
                ('assignto', models.CharField(max_length=30, verbose_name='Assign To')),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('tools', models.CharField(choices=[('Social Media', 'Social Media'), ('Email', 'Email'), ('Webinar', 'Webinar'), ('Exhabition', 'Exhabition'), ('Online ads', 'Online ads'), ('Media Ads', 'Media Ads'), ('Flyers', 'Flyers'), ('Printed clothes', 'Printed clothes'), ('Printed DeskTools', 'Printed DeskTools')], default='Social Media', max_length=100, verbose_name='Campain Tool')),
                ('targetaudiance', models.CharField(choices=[('Indviduals', 'Indviduals'), ('Companies', 'Companies')], default='Indviduals', max_length=30, verbose_name='Target Audiance')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Target Audiance Country')),
                ('industry', models.CharField(blank=True, max_length=30, null=True, verbose_name='Target Audiance Industry')),
                ('age', models.CharField(blank=True, max_length=30, null=True, verbose_name='Target Audiance Age')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30, null=True, verbose_name='Target Audiance Gender')),
                ('annualrev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Target Audiance Annual Rev.')),
                ('noemployee', models.CharField(blank=True, max_length=30, null=True, verbose_name='Target Audiance No. of Employees')),
                ('volume', models.CharField(blank=True, max_length=30, null=True, verbose_name='Audiance Volume')),
                ('duration', models.CharField(blank=True, max_length=30, null=True, verbose_name='Duration In Days')),
                ('startdate', models.DateField(blank=True, max_length=30, null=True, verbose_name='Start Date')),
                ('enddate', models.DateField(blank=True, max_length=30, null=True, verbose_name='End Date')),
                ('leadsvolume', models.CharField(blank=True, max_length=30, null=True, verbose_name='Expected Leads Volume')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Pending', max_length=30, verbose_name='Campain Status')),
                ('expenses', models.CharField(blank=True, max_length=30, null=True, verbose_name='Current Expenses')),
                ('cleadsvolume', models.CharField(blank=True, max_length=30, null=True, verbose_name='Current Leads Volume')),
                ('remarks', models.TextField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('moddate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lname',
        ),
    ]
