# Generated by Django 3.1.7 on 2021-04-23 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210423_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='createddate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Created'),
        ),
    ]
